.TH BIORHYTHM 1 "20 Oct 2013"
.SH NAME
\fBbiorhythm\fP \- biorhythm programm

.SH SYNOPSIS
.B biorhythm
[\fIOPTION\fR]... [\fIFILE\fR]...
.SH DESCRIPTION
.B biorhythm
is a biorhythm program for the desktop environment.

While aiming at simplicity and ease of use,
.B biorhythm
is a powerful and easy to use biorhythm program.

.LP
.SH OPTIONS

.TP
\fB\-\-version\fR
Output version information and exit

.SH BUGS
If you find a bug, please report it by mail to gabisoft@freesurf.ch.
.SH AUTHORS
Gabriel Mainberger (gabisoft@freesurf.ch)
